# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: abhi-agents
variables:
  workDir: '$(System.DefaultWorkingDirectory)/todo-infra'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(workDir)'
    backendServiceArm: 'todo-service-connection'
    backendAzureRmStorageAccountName: 'bhmstorage234'
    backendAzureRmContainerName: 'bhmtf'
    backendAzureRmKey: 'tf1.tfstate'
- task: TerraformTask@5
  displayName: 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(workDir)'
- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(workDir)'
    environmentServiceNameAzureRM: 'todo-service-connection'
- task: TerraformTask@5
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(workDir)'
    environmentServiceNameAzureRM: 'todo-service-connection'

